### ISSUE TITLE
Baseline

### ISSUE THREAD

**Issue by MaksymDel** [mt2017-tartu-shared-task/nmt-system-A#1]
Hi, please retrain your baseline NMT system using all the subword units as the vocabulary. Keep the train set the same as it was before, and compare BLUE scores for both the systems. 

Does it improve the score? Add a line at the end of the first report. 

Please, also take a smaller subset of your test set (e.g. 50.000 sentences) and compute BLEU on this (do not forget to undo preprocessing as described in lab3 text). Compare to the BLEU of 1000.000 and write a line about it in your report.

This way we can conclude you made additional experiments in terms of the baseline system, so you will not lose points for this.

**Comment by adfors** [comment]
We added update to the first report.
